global:
  domain: app.example.com

  keyVault:
    name: kvsecure3tier1789734694
    tenantId: 6fead228-c63b-47cb-8a02-5f1a47d082d0
    clientId: eb874a25-588d-4f6c-a164-6d2f4f91b046

frontend:
  enabled: true

  image:
    repository: acrsecure3tierv21789745065.azurecr.io/aks-3tier-frontend
    tag: "1.0.0"
    pullPolicy: IfNotPresent

  replicaCount: 2

  service:
    type: ClusterIP
    port: 80

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

api:
  enabled: true

  image:
    repository: acrsecure3tierv21789745065.azurecr.io/aks-3tier-api
    tag: "1.0.0"
    pullPolicy: IfNotPresent

  replicaCount: 2

  service:
    type: ClusterIP
    port: 3000

  serviceAccount:
    create: true
    name: api
    clientId: eb874a25-588d-4f6c-a164-6d2f4f91b046

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

  env:
    DB_HOST: secure3tier-postgres
    DB_PORT: "5432"
    DB_NAME: appdb
    DB_USER: appuser

postgres:
  enabled: true

  image:
    repository: postgres
    tag: "16-alpine"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 5432

  storage:
    size: 8Gi

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

ingress:
  enabled: true
  className: nginx

  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2

tls:
  enabled: false
  secretName: app-tls
  clusterIssuer: letsencrypt-prod

migration:
  enabled: true

  image:
    repository: node
    tag: "22-alpine"

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
