apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ printf "%s-postgres-bootstrap" .Release.Name }}
spec:
  provider: azure
  secretObjects:
    - secretName: postgres-bootstrap
      type: Opaque
      data:
        - objectName: DB-PASSWORD
          key: POSTGRES_PASSWORD
  parameters:
    usePodIdentity: "false"
    clientID: {{ .Values.global.keyVault.clientId | default "" | quote }}
    keyvaultName: {{ .Values.global.keyVault.name | default "" | quote }}
    tenantId: {{ .Values.global.keyVault.tenantId | default "" | quote }}
    cloudName: AzurePublicCloud
    objects: |
      array:
        - |
          objectName: DB-PASSWORD
          objectType: secret
