{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.serviceAccount.clientId | quote }}
{{- end }}
