{{- if and .Values.ingress.enabled .Values.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.tls.secretName }}
  labels:
    {{- include "aks-3tier-poc.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.tls.secretName }}
  issuerRef:
    name: {{ .Values.tls.clusterIssuer }}
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.global.domain }}
{{- end }}
