enabled: true
serviceAccount:
  create: true
  name: postgres
  clientId: 328a78e4-013c-4eaa-950d-15da6caf0994
image:
  repository: postgres
  tag: "16-alpine"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 5432
storage:
  size: 8Gi
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
